name: Deploy to Backend Servers

on:
  push:
    branches:
      - main  # Change this to your deployment branches

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: app

      - name: Replace Database Config with Secrets
        run: |
          sed -i "s/DBNAME/${{ secrets.DBNAME }}/g" app/dmp_config.php
          sed -i "s/DBUSER/${{ secrets.DBUSER }}/g" app/dmp_config.php
          sed -i "s/DBPASS/${{ secrets.DBPASS }}/g" app/dmp_config.php
          sed -i "s/DBHOST/${{ secrets.DBHOST }}/g" app/dmp_config.php

      - name: Set build number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Archive repository with build number
        run: tar -czvf app-${{ github.run_number }}.tar.gz ./*

      - name: Copy archive to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "app-${{ github.run_number }}.tar.gz"
          target: "/var/www/build-staging"

      - name: Extract archive and install dependencies
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/build-staging
            mkdir -p app-${{ github.run_number }}
            tar -xzvf app-${{ github.run_number }}.tar.gz -C app-${{ github.run_number }}
            # Remove existing symlink or folder
            if [ ! -f "/var/www/360apps-orchid-staging/app" ]; then
            rm -rf /var/www/360apps-orchid-staging/app
            ln -s /var/www/build-staging/app-${{ github.run_number }}/app /var/www/360apps-orchid-staging/app
            else
            ln -s /var/www/build-staging/app-${{ github.run_number }}/app /var/www/360apps-orchid-staging/app
            fi

      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "#36a64f"
          SLACK_MESSAGE: "✅ Deployment *successful* for build #${{ github.run_number }} \n Repository: ${{ github.repository }} \n Commit: ${{ github.sha }}"

  notify_failure:
    needs: deploy
    if: failure()
    runs-on: ubuntu-20.04

    steps:
      - name: Send Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "#FF0000"
          SLACK_MESSAGE: "❌ Deployment *failed* for build #${{ github.run_number }} \n Repository: ${{ github.repository }} \n Commit: ${{ github.sha }} \n Check logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
