name: Deploy to Backend Server

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: app

      - name: Set build number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Archive repository with build number
        run: tar -czvf app-${{ env.BUILD_NUMBER }}.tar.gz ./*

      - name: Copy archive to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app-${{ env.BUILD_NUMBER }}.tar.gz"
          target: "/var/www/build-staging"

      - name: Extract archive and install dependencies
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/build-staging
            mkdir -p app-${{ github.run_number }}
            tar -xzvf app-${{ github.run_number }}.tar.gz -C app-${{ github.run_number }}
            ln -s /var/www/build-staging/app-${{ github.run_number }}/app /var/www/360apps-orchid-staging/app
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
